---
- name: "Check for version 16.04"
  fail: msg="Must be version 16.04 or higher"
  when: ansible_distribution_version | version_compare('16.04', '<')

- include_tasks: firewall.yml
  when: DOCKER_BUILD is undefined or DOCKER_BUILD == 'no'
  tags: firewall

- include_tasks: deps.yml
  tags: deps

- include_tasks: unattended_updates.yml
  tags: deps
