---
development: False

app_user: cif
app_group: "{{ app_user }}"
app_user_home: "/home/{{ app_user }}"

cif_runtime_path: '/var/lib/cif'
cif_router_config_path: '/etc/cif/cif-router.yml'
cif_store_store: 'sqlite'
cif_hunter_exclude: 'osint.bambenekconsulting.com:dga'
cif_hunter_threads: 0
cif_gatherer_geo_fqdn: 0

csirtg_smrt_runtime_path: "{{ cif_runtime_path }}"
csirtg_smrt_cache_path: "{{ cif_runtime_path }}/smrt"
csirtg_smrt_config_path: '/etc/cif/csirtg-smrt.yml'
csirtg_smrt_rules_path: '/etc/cif/rules'
csirtg_smrt_fireball_size: 500
csirtg_smrt_goback_days: 3

geoip_userid: 999999
geoip_key: "000000000000"
geoip_products: GeoLite2-City GeoLite2-Country GeoLite-Legacy-IPv6-City GeoLite-Legacy-IPv6-Country 506 517 533

nginx_key_file: /etc/nginx/ssl/nginx.key
nginx_cert_file: /etc/nginx/ssl/nginx.crt
nginx_conf_file: /etc/nginx/sites-available/default
nginx_server_name: localhost